max_width = 82
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
wrap_comments = true
format_code_in_doc_comments = true
comment_width = 80
normalize_comments = true
normalize_doc_attributes = true
